### ISSUE TITLE
Implement opc ua certificate management tool  

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#394]
A tool is required to manage certificates, The tool is intended to support the following functions.

- [x] Tool to manage self signed certificates (https://github.com/ASNeG/OpcUaStack/issues/395)
- [x] Tool to manage ca certificates (https://github.com/ASNeG/OpcUaStack/issues/396)
- [x] Tool to manage issuer certificates (https://github.com/ASNeG/OpcUaStack/issues/405)
- [x] Tool to manage application certificates (https://github.com/ASNeG/OpcUaStack/issues/397)
- [x] Tool to manage certificates (https://github.com/ASNeG/OpcUaStack/issues/398)
- [x] Open ssl template configuration (https://github.com/ASNeG/OpcUaStack/issues/399)
- [ ] Document the use of certificates (https://github.com/ASNeG/OpcUaStack/issues/400)
